# Form implementation generated from reading ui file '.\deposit_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_deposit_window(object):
    def setupUi(self, deposit_window):
        deposit_window.setObjectName("deposit_window")
        deposit_window.resize(276, 116)
        self.gridLayout = QtWidgets.QGridLayout(deposit_window)
        self.gridLayout.setObjectName("gridLayout")
        self.balanceLabel = QtWidgets.QLabel(deposit_window)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.balanceLabel.setFont(font)
        self.balanceLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.balanceLabel.setObjectName("balanceLabel")
        self.gridLayout.addWidget(self.balanceLabel, 0, 0, 1, 2)
        self.depositTextEdit = QtWidgets.QPlainTextEdit(deposit_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depositTextEdit.sizePolicy().hasHeightForWidth())
        self.depositTextEdit.setSizePolicy(sizePolicy)
        self.depositTextEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.depositTextEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.depositTextEdit.setObjectName("depositTextEdit")
        self.gridLayout.addWidget(self.depositTextEdit, 1, 0, 1, 2)
        self.depositButton = QtWidgets.QPushButton(deposit_window)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.depositButton.setFont(font)
        self.depositButton.setObjectName("depositButton")
        self.gridLayout.addWidget(self.depositButton, 2, 0, 1, 1)
        self.backButton = QtWidgets.QPushButton(deposit_window)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.backButton.setFont(font)
        self.backButton.setObjectName("backButton")
        self.gridLayout.addWidget(self.backButton, 2, 1, 1, 1)

        self.retranslateUi(deposit_window)
        QtCore.QMetaObject.connectSlotsByName(deposit_window)

    def retranslateUi(self, deposit_window):
        _translate = QtCore.QCoreApplication.translate
        deposit_window.setWindowTitle(_translate("deposit_window", "存款"))
        self.balanceLabel.setText(_translate("deposit_window", "余额：0"))
        self.depositTextEdit.setPlainText(_translate("deposit_window", "0"))
        self.depositButton.setText(_translate("deposit_window", "存入"))
        self.backButton.setText(_translate("deposit_window", "返回"))
