# Form implementation generated from reading ui file '.\transfer_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_transfer_window(object):
    def setupUi(self, transfer_window):
        transfer_window.setObjectName("transfer_window")
        transfer_window.resize(295, 206)
        self.gridLayout = QtWidgets.QGridLayout(transfer_window)
        self.gridLayout.setObjectName("gridLayout")
        self.balanceLabel = QtWidgets.QLabel(transfer_window)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.balanceLabel.setFont(font)
        self.balanceLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.balanceLabel.setObjectName("balanceLabel")
        self.gridLayout.addWidget(self.balanceLabel, 0, 0, 1, 1)
        self.transferLabel = QtWidgets.QLabel(transfer_window)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.transferLabel.setFont(font)
        self.transferLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.transferLabel.setObjectName("transferLabel")
        self.gridLayout.addWidget(self.transferLabel, 1, 0, 1, 1)
        self.transferTextEdit = QtWidgets.QPlainTextEdit(transfer_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transferTextEdit.sizePolicy().hasHeightForWidth())
        self.transferTextEdit.setSizePolicy(sizePolicy)
        self.transferTextEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.transferTextEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.transferTextEdit.setObjectName("transferTextEdit")
        self.gridLayout.addWidget(self.transferTextEdit, 2, 0, 1, 2)
        self.targetCardLabel = QtWidgets.QLabel(transfer_window)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.targetCardLabel.setFont(font)
        self.targetCardLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.targetCardLabel.setObjectName("targetCardLabel")
        self.gridLayout.addWidget(self.targetCardLabel, 3, 0, 1, 1)
        self.targetCardTextEdit = QtWidgets.QPlainTextEdit(transfer_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.targetCardTextEdit.sizePolicy().hasHeightForWidth())
        self.targetCardTextEdit.setSizePolicy(sizePolicy)
        self.targetCardTextEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.targetCardTextEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.targetCardTextEdit.setObjectName("targetCardTextEdit")
        self.gridLayout.addWidget(self.targetCardTextEdit, 4, 0, 1, 2)
        self.transferButton = QtWidgets.QPushButton(transfer_window)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.transferButton.setFont(font)
        self.transferButton.setObjectName("transferButton")
        self.gridLayout.addWidget(self.transferButton, 5, 0, 1, 1)
        self.backButton = QtWidgets.QPushButton(transfer_window)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.backButton.setFont(font)
        self.backButton.setObjectName("backButton")
        self.gridLayout.addWidget(self.backButton, 5, 1, 1, 1)

        self.retranslateUi(transfer_window)
        QtCore.QMetaObject.connectSlotsByName(transfer_window)

    def retranslateUi(self, transfer_window):
        _translate = QtCore.QCoreApplication.translate
        transfer_window.setWindowTitle(_translate("transfer_window", "转账"))
        self.balanceLabel.setText(_translate("transfer_window", "余额：0"))
        self.transferLabel.setText(_translate("transfer_window", "转账金额"))
        self.transferTextEdit.setPlainText(_translate("transfer_window", "0"))
        self.targetCardLabel.setText(_translate("transfer_window", "收款卡号"))
        self.transferButton.setText(_translate("transfer_window", "转账"))
        self.backButton.setText(_translate("transfer_window", "返回"))
