# Form implementation generated from reading ui file '.\verification_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VericationWindow(object):
    def setupUi(self, VericationWindow):
        VericationWindow.setObjectName("VericationWindow")
        VericationWindow.resize(275, 173)
        self.gridLayout = QtWidgets.QGridLayout(VericationWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.cardNumLabel = QtWidgets.QLabel(VericationWindow)
        self.cardNumLabel.setObjectName("cardNumLabel")
        self.verticalLayout.addWidget(self.cardNumLabel)
        self.cardNumTextEdit = QtWidgets.QPlainTextEdit(VericationWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardNumTextEdit.sizePolicy().hasHeightForWidth())
        self.cardNumTextEdit.setSizePolicy(sizePolicy)
        self.cardNumTextEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.cardNumTextEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.cardNumTextEdit.setObjectName("cardNumTextEdit")
        self.verticalLayout.addWidget(self.cardNumTextEdit)
        self.passwordLabel = QtWidgets.QLabel(VericationWindow)
        self.passwordLabel.setObjectName("passwordLabel")
        self.verticalLayout.addWidget(self.passwordLabel)
        self.passwordTextEdit = QtWidgets.QPlainTextEdit(VericationWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordTextEdit.sizePolicy().hasHeightForWidth())
        self.passwordTextEdit.setSizePolicy(sizePolicy)
        self.passwordTextEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.passwordTextEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.passwordTextEdit.setObjectName("passwordTextEdit")
        self.verticalLayout.addWidget(self.passwordTextEdit)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 2)
        self.loginButton = QtWidgets.QPushButton(VericationWindow)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.loginButton.setFont(font)
        self.loginButton.setObjectName("loginButton")
        self.gridLayout.addWidget(self.loginButton, 1, 0, 1, 1)
        self.backButton = QtWidgets.QPushButton(VericationWindow)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.backButton.setFont(font)
        self.backButton.setObjectName("backButton")
        self.gridLayout.addWidget(self.backButton, 1, 1, 1, 1)

        self.retranslateUi(VericationWindow)
        QtCore.QMetaObject.connectSlotsByName(VericationWindow)

    def retranslateUi(self, VericationWindow):
        _translate = QtCore.QCoreApplication.translate
        VericationWindow.setWindowTitle(_translate("VericationWindow", "登录"))
        self.cardNumLabel.setText(_translate("VericationWindow", "卡号"))
        self.passwordLabel.setText(_translate("VericationWindow", "密码"))
        self.loginButton.setText(_translate("VericationWindow", "登录"))
        self.backButton.setText(_translate("VericationWindow", "返回"))
