[package]
name = "automated_teller_machine_system"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
mysql = "24.0.0"
ratatui = "0.24.0"
rust_decimal = "1.33.1"
url = "2.5.0"
